import "../styles/globals.css";
import { ThemeProvider } from "../theme-provider/theme.jsx";

export const metadata = {
  title: "Ngopilu.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
